# -- Main Menu --
# 中華AI應用發展協會主選單配置

[[main]]
  name = "首頁"
  pageRef = "/"
  weight = 10

[[main]]
  name = "關於協會"
  pageRef = "about"
  weight = 20

[[main]]
  name = "協會章程"
  parent = "關於協會"
  pageRef = "about/charter"
  weight = 21

[[main]]
  name = "會員制度"
  pageRef = "membership"
  weight = 30

[[main]]
  name = "活動項目"
  pageRef = "activities"
  weight = 40

[[main]]
  name = "協會新聞"
  pageRef = "news"
  weight = 45

[[main]]
  name = "聯絡我們"
  pageRef = "about"
  weight = 50
